name: kurdish_localization_flutter
description: This package provides localization support for Kurdish locale 
version: 0.0.4
homepage: "https://github.com/gauravmehta13/kurdish_localization_flutter"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
