library kurdish_localization;

export 'package:kurdish_localization_flutter/ku_material_localization_delegate.dart';
export 'package:kurdish_localization_flutter/ku_widget_localization_delegate.dart';
